dz-groupware/frontend

package-lock.json, package.json, src/App.js, src/components/CompanyMgmt/CompanyMgmtAside.jsx, src/components/CompanyMgmt/CompanyMgmtInfo.jsx, src/components/CompanyMgmt/CompanyMgmtNav.jsx
=> [chore] : 일부 에러수정

package-lock.json, package.json, src/App.js, src/components/Commons/StyledForm.jsx, src/components/CompanyMgmt/CompanyMgmtAside.jsx, src/components/CompanyMgmt/CompanyMgmtForm.jsx, src/components/CompanyMgmt/CompanyMgmtInfo.jsx, src/components/CompanyMgmt/CompanyMgmtNav.jsx
[fix]: 회사관리페이지 수정
api 요청 부분 수정
style변경
=> [fix]: 회사관리페이지 수정

src/api/companymgmt.js, src/api/employeemgmt.js, src/components/CompanyMgmt/CompanyMgmtAside.jsx, src/components/EmployeeMgmt/EmployeeMgmtAside.jsx, src/pages/Module.js
=> [fix]: api 데이터 요청 형식 수정

src/api/employeemgmt.js, src/components/Commons/MgmtMain.jsx, src/components/Commons/MgmtNav.jsx, src/components/Commons/StyledButton.jsx, src/components/Commons/StyledForm.jsx, src/components/CompanyMgmt/CompanyMgmtAside.jsx, src/components/CompanyMgmt/CompanyMgmtForm.jsx, src/components/CompanyMgmt/CompanyMgmtNav.jsx, src/components/EmployeeMgmt/EmployeeMgmtAside.jsx, src/components/EmployeeMgmt/EmployeeMgmtBasicForm.jsx, src/components/EmployeeMgmt/EmployeeMgmtForm.jsx, src/components/EmployeeMgmt/EmployeeMgmtGroupForm.jsx, src/components/EmployeeMgmt/EmployeeMgmtHeader.jsx, src/components/EmployeeMgmt/EmployeeMgmtInfo.jsx, src/components/EmployeeMgmt/EmployeeMgmtNav.jsx, src/pages/EmployeeMgmtPage.jsx, src/pages/Home.jsx, src/utils/Slice.js
사원 등록 기능 추가
탭 전환시 데이터 추가
회사관리 페이지 버그수정
=> [feat]: 사원등록 기능 추가 및 버그 수정

src/components/EmployeeMgmt/EmployeeMgmtAside.jsx, src/components/EmployeeMgmt/EmployeeMgmtGroupForm.jsx, src/components/EmployeeMgmt/EmployeeMgmtInfo.jsx
=> [feat]: 부서 추가 기능

src/api/companymgmt.js, src/api/employeemgmt.js, src/components/CompanyMgmt/CompanyMgmtAside.jsx, src/components/CompanyMgmt/CompanyMgmtForm.jsx, src/components/CompanyMgmt/CompanyMgmtInfo.jsx, src/components/CompanyMgmt/CompanyMgmtNav.jsx, src/components/EmployeeMgmt/EmployeeMgmtAside.jsx, src/components/EmployeeMgmt/EmployeeMgmtBasicForm.jsx, src/components/EmployeeMgmt/EmployeeMgmtForm.jsx, src/components/EmployeeMgmt/EmployeeMgmtGroupForm.jsx, src/components/EmployeeMgmt/EmployeeMgmtInfo.jsx, src/components/EmployeeMgmt/EmployeeMgmtNav.jsx, src/pages/CompanyMgmtPage.jsx, src/pages/EmployeeMgmtPage.jsx, src/utils/thunk.js
=> [fix]: pageId 버그 수정

src/api/employeemgmt.js, src/components/EmployeeMgmt/EmployeeMgmtAside.jsx, src/components/EmployeeMgmt/EmployeeMgmtBasicForm.jsx, src/components/EmployeeMgmt/EmployeeMgmtGroupForm.jsx, src/components/EmployeeMgmt/EmployeeMgmtHeader.jsx, src/components/EmployeeMgmt/EmployeeMgmtInfo.jsx, src/components/GNB/GNB.jsx, src/pages/EmployeeMgmtPage.jsx, src/pages/Module.js, src/utils/Slice.js, src/utils/axiosInstance.js
image 업로드 기능 수정 
에러처리 등
페이지네이션 추가
퇴사처리 모달 추가
=> [feat]: image 업로드기능 수정 및 페이지네이션 추가 퇴사처리 모달 추가

src/api/gnb.js, src/api/login.js, src/components/TB/OrgModal.jsx, src/components/TB/PosiList.jsx, src/components/TB/Profile.jsx, src/components/TB/ProfileModal.jsx, src/pages/GnbLayout.jsx, src/pages/LnbLayout.jsx, src/pages/Module.js, src/pages/TB.jsx, src/utils/axiosInstance.js
- 로그인 정보 없이 기본 경로로 이동
: 로그인 페이지로 이동
- 새로고침시에 route-list 없는 문제
=> [refactor]: 페이지 이동시 생기는 문제 

src/api/department.js, src/api/login.js, src/api/menu.js, src/components/DepartmentManager/DeptItem.jsx, src/components/DepartmentManager/DetailBasic.jsx, src/components/DepartmentManager/DetailEmp.jsx, src/components/DepartmentManager/DetailTitle.jsx, src/components/DepartmentManager/SearchForm.jsx, src/components/DepartmentManager/SearchResult.jsx, src/components/DepartmentManager/TitleBtn.jsx, src/components/TB/Recent.jsx, src/pages/DepartmentManager.jsx, src/pages/GnbLayout.jsx, src/pages/LnbLayout.jsx, src/pages/Main.jsx, src/pages/MenuEditor.jsx
- 부서 상위에서 자신의 하위로 저장하는 로직 수정 중
=> [refactor]: 부서 페이지 기능 에러 수정(수정 중)

src/components/EmployeeMgmt/EmployeeMgmtGroupForm.jsx, src/components/EmployeeMgmt/EmployeeMgmtInfo.jsx
=> [fix]: 사원관리 부서정보로직 수정

src/api/company.js, src/components/TB/ProfileModal.jsx, src/pages/LoginPage.jsx, src/utils/axiosInstance.js
isLogin 로컬스토리지에 추가 => 로그인중인지 아닌지 확인용
=> [fix]: 로그인한 후에 로그인 페이지 Hello컴포넌트 출력되게 수정

src/utils/axiosInstance.js
=> [test]: url변경

src/api/employeemgmt.js, src/components/Commons/MgmtInfo.jsx, src/components/CompanyMgmt/CompanyMgmtAside.jsx, src/components/CompanyMgmt/CompanyMgmtForm.jsx, src/components/CompanyMgmt/CompanyMgmtInfo.jsx, src/components/CompanyMgmt/CompanyMgmtNav.jsx, src/components/EmployeeMgmt/EmployeeMgmtAside.jsx, src/components/EmployeeMgmt/EmployeeMgmtGroupForm.jsx, src/utils/Slice.js, src/utils/axiosInstance.js
=> [feat]: 회사,사원  삭제 및 저장에 대한 권한 수정

src/components/CompanyMgmt/CompanyMgmtInfo.jsx, src/components/EmployeeMgmt/EmployeeMgmtAside.jsx, src/components/EmployeeMgmt/EmployeeMgmtBasicForm.jsx, src/components/EmployeeMgmt/EmployeeMgmtGroupForm.jsx, src/components/EmployeeMgmt/EmployeeMgmtInfo.jsx, src/utils/Slice.js
=> [feat]: 사원관리-부서정보  로직 수정

src/components/RoleMapping/Menu/MappingMenuTreeTop.jsx, src/components/RoleSetting/Menu/MenuTreeTop.jsx, src/pages/RoleMappingPage.jsx, src/pages/RoleSettingPage.jsx
=> [fix]: 버튼 크기 수정

src/utils/axiosInstance.js
=> [fix]: 배포테스트

src/components/TB/PosiList.jsx, src/pages/LoginPage.jsx, src/pages/TB.jsx
=> [fix]: 홈으로 가게끔 수정

src/components/EmployeeMgmt/EmployeeMgmtHeader.jsx, src/components/RoleSetting/Menu/MenuOfAuthEditor.jsx
=> [fix]: 메시지 수정

src/utils/axiosInstance.js
=> [docs]: 배포용 링크로 수정

src/index.js, src/pages/RoleMappingPage.jsx
=> [test]: 무한스크롤 버그 수정

src/components/EmployeeMgmt/EmployeeMgmtGroupForm.jsx, src/components/EmployeeMgmt/EmployeeMgmtInfo.jsx, src/utils/axiosInstance.js
=> [fix]: 사원관리 부서정보 소속회사 로직 수정 및 복구 로직 수정

src/components/EmployeeMgmt/EmployeeMgmtGroupForm.jsx, src/components/TB/Recent.jsx
=> [fix]: 부서정보 리스트 및 최근기록 링크 수정

src/components/EmployeeMgmt/EmployeeMgmtGroupForm.jsx, src/components/TB/Recent.jsx, src/utils/axiosInstance.js
=> [fix]: 사원관리 부서정보 수정

src/components/EmployeeMgmt/EmployeeMgmtInfo.jsx, src/utils/axiosInstance.js
=>  [fix]: 부서정보 입사일 로직 수정

src/utils/axiosInstance.js
=> [fix]: 배포URL 수정

src/components/EmployeeMgmt/EmployeeMgmtHeader.jsx
=> [fix]: 일괄퇴사처리시 데이터형태 수정
